apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hello-pod
    template:
        metadata:
            labels:
                app: hello-pod
        spec:
            containers:
                - name: hello-container
                  image: van6065/hello-nodejs
