apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hello-pod
    template:
        metadata:
            labels:
                app: hello-pod
        spec:
            containers:
                - name: hello-container
                  image: van6065/hello-nodejs
---
apiVersion: v1
kind: Service
metadata:
    name: hello-node-port
spec:
    type: NodePort
    ports:
        - port: 3000
          protocol: TCP
          nodePort: 31000
    selector:
        app: hello-pod
